spring:
  application:
    name: todo-app
  datasource:
    url: jdbc:postgresql://db:5432/db_todo-app
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
